version: '3.8'

services:
  db:
    image: postgres:17.4
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: calorie_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    restart: always
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/calorie_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network: